### ISSUE TITLE
sysvipc handling is time64-incompatible

### ISSUE THREAD

**Issue by richfelker** [strace/strace#116] opened 2019-12-24 07:12 UTC
(Apologies if this is a duplicate of something already reported here or elsewhere. I could have sworn I already reported and had communication about it, but I can't find record of that anywhere.)

strace gets the structure definitions and command macro values from `sys/ipc.h`, `sys/sem.h`, etc. only falling back to the kernel uapi headers if these are missing. However, for moving 32-bit archs to 64-bit `time_t`, the application-facing/libc types for `semid_ds`, etc. must necessarily mismatch the kernel types since the existing time fields lack correct alignment (and on some archs, even lack padding) to be expanded/used in-place.

Since strace wants to be working with the structures and command numbers present in the tracee's interface with the kernel, not its own interface with libc, it should be including the kernel uapi headers for these definitions.

Original report and analysis was on the musl libc list in regards to time64 conversion: https://www.openwall.com/lists/musl/2019/10/29/7

**Comment by ldv-alt** [comment] 2020-01-14 02:17
On Mon, Dec 23, 2019 at 11:12:04PM -0800, Rich Felker wrote:
> (Apologies if this is a duplicate of something already reported here or elsewhere. I could have sworn I already reported and had communication about it, but I can't find record of that anywhere.)

Yes, you've commented on this subject already, see
https://lists.strace.io/pipermail/strace-devel/2019-November/009223.html

> strace gets the structure definitions and command macro values from `sys/ipc.h`, `sys/sem.h`, etc. only falling back to the kernel uapi headers if these are missing. However, for moving 32-bit archs to 64-bit `time_t`, the application-facing/libc types for `semid_ds`, etc. must necessarily mismatch the kernel types since the existing time fields lack correct alignment (and on some archs, even lack padding) to be expanded/used in-place.
> 
> Since strace wants to be working with the structures and command numbers present in the tracee's interface with the kernel, not its own interface with libc, it should be including the kernel uapi headers for these definitions.

According to strace testsuite, this change, unfortunately, causes
regressions: the structures returned by msgctl and shmctl syscalls are
no longer printed correctly for some architectures.  For example, this
happens with x32 tracee on x86_64 and with 32-bit tracee on sparc64.
Compared with glibc headers, kernel UAPI headers are apparently not good
enough for this job and have to be fixed first.

https://lists.strace.io/pipermail/strace-devel/2019-November/009250.html

**Comment by richfelker** [comment] 2020-01-14 02:25
Since it will probably need to be supported to build with old kernel uapi headers for a long while, what about updating the configure test to prefer kernel headers but reject them if x32 ABI mismatch is detected in them, falling back to libc headers in that case?

**Comment by arndb** [comment] 2020-01-14 09:27
Can you be more specific about what the problem is with the uapi headers? I looked at them again now but fail to see what's wrong with them.

**Comment by ldv-alt** [comment] 2020-01-14 09:59
On Tue, Jan 14, 2020 at 01:27:09AM -0800, arndb wrote:
> Can you be more specific about what the problem is with the uapi headers? I looked at them again now but fail to see what's wrong with them.

x32: I cannot reproduce it any longer where I used to, maybe something has
been fixed in uapi for x32.

sparc:
according to struct compat_ipc64_perm defined in arch/sparc/include/asm/compat.h,
the type of uid is __compat_uid32_t aka u32,
but, according to struct ipc64_perm defined in arch/sparc/include/uapi/asm/ipcbuf.h,
the type of uid is __kernel_uid_t which is defined to unsigned short on sparc.

I suppose the regression was introduced by commit
83c86984bff2d793c91eb710af7857828b9ddb49 aka v2.6.29-rc1~501^2~6

If my guess is correct, then the only working form of IPC_STAT on sparc32
since that commit is sparc64 in compat mode.

**Comment by arndb** [comment] 2020-01-14 10:55
On Tue, Jan 14, 2020 at 10:59 AM Dmitry V. Levin <notifications@github.com>
wrote:

> On Tue, Jan 14, 2020 at 01:27:09AM -0800, arndb wrote:
> > Can you be more specific about what the problem is with the uapi
> headers? I looked at them again now but fail to see what's wrong with them.
>
> x32: I cannot reproduce it any longer where I used to, maybe something has
> been fixed in uapi for x32.
>

Ok, this is know to have been broken in uapi headers between v4.3 and v4.17.

See commits f4b4aae18288 ("x86/headers/uapi: Fix __BITS_PER_LONG value
for x32 builds") and 1a512c0882bd ("x86/ipc: Fix x32 version of shmid64_ds
and
msqid64_ds").


> sparc:
> according to struct compat_ipc64_perm defined in
> arch/sparc/include/asm/compat.h,
> the type of uid is __compat_uid32_t aka u32,
> but, according to struct ipc64_perm defined in
> arch/sparc/include/uapi/asm/ipcbuf.h,
> the type of uid is __kernel_uid_t which is defined to unsigned short on
> sparc.
>
> I suppose the regression was introduced by commit
> 83c86984bff2d793c91eb710af7857828b9ddb49 aka v2.6.29-rc1~501^2~6
>
> If my guess is correct, then the only working form of IPC_STAT on sparc32
> since that commit is sparc64 in compat mode.


Ok, so this would be a bug with what sysvipc on sparc32 does in the kernel,
rather than a bug of the uapi headers not describing what it does, correct?

Adding the SPARC list and maintainer to Cc. Yes, I read it the same way.
In particular, Sam back then wrote

commit 83c86984bff2d793c91eb710af7857828b9ddb49
Author: Sam Ravnborg <sam@ravnborg.org>
Date:   Sun Jan 4 15:44:22 2009 -0800

    sparc: unify ipcbuf.h

    The ony difference is the size of the mode.
    sparc has extra padding to compensate for this.

    Signed-off-by: Sam Ravnborg <sam@ravnborg.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

However, aside from mode, the other fields that were changed are
'uid', 'gid', 'cuid' and 'cgid'. It's been 11 years since that ABI change,
so I wonder if anyone has started relying on the changed behavior
in the meantime, or sparc32 users just don't use sysvipc.

I checked glibc and uclibc-ng, and both use the pre-2009 version
of the ABI. I also checked the leon-linux patches from
https://www.gaisler.com/anonftp/linux/linux-2.6/kernel/ to see
if they had already come across this, but there is no fix either.

       Arnd

**Comment by ldv-alt** [comment] 2020-01-14 11:29
On Tue, Jan 14, 2020 at 02:55:08AM -0800, arndb wrote:
[...]
> > x32: I cannot reproduce it any longer where I used to, maybe something has
> > been fixed in uapi for x32.
> 
> Ok, this is know to have been broken in uapi headers between v4.3 and v4.17.
> 
> See commits f4b4aae18288 ("x86/headers/uapi: Fix __BITS_PER_LONG value
> for x32 builds") and 1a512c0882bd ("x86/ipc: Fix x32 version of shmid64_ds
> and msqid64_ds").

Great!

> > sparc:
> > according to struct compat_ipc64_perm defined in
> > arch/sparc/include/asm/compat.h,
> > the type of uid is __compat_uid32_t aka u32,
> > but, according to struct ipc64_perm defined in
> > arch/sparc/include/uapi/asm/ipcbuf.h,
> > the type of uid is __kernel_uid_t which is defined to unsigned short on
> > sparc.
> >
> > I suppose the regression was introduced by commit
> > 83c86984bff2d793c91eb710af7857828b9ddb49 aka v2.6.29-rc1~501^2~6
> >
> > If my guess is correct, then the only working form of IPC_STAT on sparc32
> > since that commit is sparc64 in compat mode.
> 
> Ok, so this would be a bug with what sysvipc on sparc32 does in the kernel,
> rather than a bug of the uapi headers not describing what it does, correct?

Not really, from strace testsuite perspective it looks like tracing of
32-bit processes by 64-bit strace produces wrong results on sparc64 when
strace is built with uapi headers instead of glibc headers, and this
happens because arch/sparc/include/uapi/asm/ipcbuf.h does not describe
the same structure the sparc64 kernel works with in to_compat_ipc64_perm.

So I'd say it's a bug of arch/sparc/include/uapi/asm/ipcbuf.h not
describing what ipc/compat.c actually does.

I've never had access to a sparc32 kernel to check what's going on there,
but ...

> Adding the SPARC list and maintainer to Cc. Yes, I read it the same way.
> In particular, Sam back then wrote
> 
> commit 83c86984bff2d793c91eb710af7857828b9ddb49
> Author: Sam Ravnborg <sam@ravnborg.org>
> Date:   Sun Jan 4 15:44:22 2009 -0800
> 
>     sparc: unify ipcbuf.h
> 
>     The ony difference is the size of the mode.
>     sparc has extra padding to compensate for this.
> 
>     Signed-off-by: Sam Ravnborg <sam@ravnborg.org>
>     Signed-off-by: David S. Miller <davem@davemloft.net>
> 
> However, aside from mode, the other fields that were changed are
> 'uid', 'gid', 'cuid' and 'cgid'. It's been 11 years since that ABI change,
> so I wonder if anyone has started relying on the changed behavior
> in the meantime, or sparc32 users just don't use sysvipc.
> 
> I checked glibc and uclibc-ng, and both use the pre-2009 version
> of the ABI. I also checked the leon-linux patches from
> https://www.gaisler.com/anonftp/linux/linux-2.6/kernel/ to see
> if they had already come across this, but there is no fix either.

... this definitely means users of sparc32 kernel (if any) don't use
IPC_STAT since 2009.


-- 
ldv

**Comment by arndb** [comment] 2020-01-14 11:37
On Tue, Jan 14, 2020 at 12:29 PM Dmitry V. Levin
<notifications@github.com> wrote:
> On Tue, Jan 14, 2020 at 02:55:08AM -0800, arndb wrote:
> > > sparc:
> > > according to struct compat_ipc64_perm defined in
> > > arch/sparc/include/asm/compat.h,
> > > the type of uid is __compat_uid32_t aka u32,
> > > but, according to struct ipc64_perm defined in
> > > arch/sparc/include/uapi/asm/ipcbuf.h,
> > > the type of uid is __kernel_uid_t which is defined to unsigned short on
> > > sparc.
> > >
> > > I suppose the regression was introduced by commit
> > > 83c86984bff2d793c91eb710af7857828b9ddb49 aka v2.6.29-rc1~501^2~6
> > >
> > > If my guess is correct, then the only working form of IPC_STAT on sparc32
> > > since that commit is sparc64 in compat mode.
> >
> > Ok, so this would be a bug with what sysvipc on sparc32 does in the kernel,
> > rather than a bug of the uapi headers not describing what it does, correct?
>
> Not really, from strace testsuite perspective it looks like tracing of
> 32-bit processes by 64-bit strace produces wrong results on sparc64 when
> strace is built with uapi headers instead of glibc headers, and this
> happens because arch/sparc/include/uapi/asm/ipcbuf.h does not describe
> the same structure the sparc64 kernel works with in to_compat_ipc64_perm.
>
> So I'd say it's a bug of arch/sparc/include/uapi/asm/ipcbuf.h not
> describing what ipc/compat.c actually does.

Fair enough. The header matches the behavior of the native kernel,
but both the header and the kernel are wrong, you are just lucky
that in compat mode the glibc headers describe what the kernel does.

> > Adding the SPARC list and maintainer to Cc. Yes, I read it the same way.
> > In particular, Sam back then wrote
> >
> > commit 83c86984bff2d793c91eb710af7857828b9ddb49
> > Author: Sam Ravnborg <sam@ravnborg.org>
> > Date: Sun Jan 4 15:44:22 2009 -0800
> >
> > sparc: unify ipcbuf.h
> >
> > The ony difference is the size of the mode.
> > sparc has extra padding to compensate for this.
> >
> > Signed-off-by: Sam Ravnborg <sam@ravnborg.org>
> > Signed-off-by: David S. Miller <davem@davemloft.net>
> >
> > However, aside from mode, the other fields that were changed are
> > 'uid', 'gid', 'cuid' and 'cgid'. It's been 11 years since that ABI change,
> > so I wonder if anyone has started relying on the changed behavior
> > in the meantime, or sparc32 users just don't use sysvipc.
> >
> > I checked glibc and uclibc-ng, and both use the pre-2009 version
> > of the ABI. I also checked the leon-linux patches from
> > https://www.gaisler.com/anonftp/linux/linux-2.6/kernel/ to see
> > if they had already come across this, but there is no fix either.
>
> ... this definitely means users of sparc32 kernel (if any) don't use
> IPC_STAT since 2009.

I can see that it's being tested for each glibc release,
e.g. https://sourceware.org/glibc/wiki/Release/2.30#SPARC_.2832-bit.29
and it's probably a release blocker, but I guess that this has also
been done on compat mode since at least 2009, rather than
on native 32-bit sparc hardware.

       Arnd

**Comment by richfelker** [comment] 2020-01-14 21:39
Now that fix is in progress on the kernel side, what should the action on the strace side be? I think the choices are roughly:

1. Default to using kernel uapi headers with a test for whether they're broken (only needed on x32 and sparc32), falling back to libc ones if so. Users of a libc with time64 will have to ensure they have fixed uapi headers.

2. Default to using libc headers unless arch is 32-bit and time_t is 64-bit. In that case, fallback to kernel uapi headers.

I like approach 1 better because it's semantically correct, and would also work if libc were just using different structures to interface with applications independent of anything to do with time_t. The definitions strace wants here really are the ones defining the ABI between user and kernel space, not between application and libc.

**Comment by ldv-alt** [comment] 2020-01-16 16:47
On Tue, Jan 14, 2020 at 01:39:33PM -0800, Rich Felker wrote:
> Now that fix is in progress on the kernel side, what should the action on the strace side be? I think the choices are roughly:
> 
> 1. Default to using kernel uapi headers with a test for whether they're broken (only needed on x32 and sparc32), falling back to libc ones if so. Users of a libc with time64 will have to ensure they have fixed uapi headers.

The check would be needed not just on x32 and sparc32 but also on x86_64 and sparc64 because the part of strace that handles compat syscalls is built in a special way to obtain the correct representation of compat data types.

**Comment by richfelker** [comment] 2020-01-16 16:56
I see. Could a configure-time test determine if uapi headers are broken by asserting struct sizes or similar?

**Closed** 2020-01-17 22:51 UTC

**Comment by richfelker** [comment] 2020-01-18 05:41
Looks good! Thanks!
