### ISSUE TITLE
riscv64: First syscall argument missing when GET_SYSCALL_INFO is disabled

### ISSUE THREAD

**Issue by andreabolognani** [strace/strace#315] opened 2024-09-13 17:24 UTC
Distro packages for strace seem to disable the test suite on riscv64 (see for example [Fedora](http://fedora.riscv.rocks:3000/rpms/strace/src/commit/37fbe25da5896569c05efd0f2b8c4f01010bbe87/strace.spec#L109-L113) and [Debian](https://salsa.debian.org/debian/strace/-/blob/b225a340e2af5fe0cbe035cebb08738eb6b88da8/debian/rules#L59-63)).

I recently tried building the latest Fedora package on riscv64 with test suite enabled and it mostly worked fine, with the exception of a single failure for `tests/legacy_syscall_info.test`. Minimal reproducer that displays the issue:

```
$ ./src/strace /
execve("/", ["/"], 0x3fd7194e00 /* 35 vars */) = -1 EACCES (Permission denied)
./src/strace: exec: Permission denied
+++ exited with 1 +++

$ ./src/disable_ptrace_get_syscall_info ./src/strace /
execve(0xffffffffffffffda, ["/"], 0x3fe6949df0 /* 35 vars */) = -1 EACCES (Permission denied)
./src/strace: exec: Permission denied
+++ exited with 1 +++
```

No matter what program is run under strace and which syscalls it uses, the first argument to any syscall is always reported as `0xffffffffffffffda` when `PTRACE_GET_SYSCALL_INFO` is not available. All the other argument are fine.

I've sprinkled `tprintf_string()` all over the place, notably in `ptrace_setregset()`, and based on what I've seen it's not some code in strace itself that causes the bogus value to be reported: if I inspect `riscv_regs.a0` immediately after calling `strace()`, I can see that the previous value has been overwritten by the syscall.

So either there's a bug in the kernel, or strace needs to do something different to get the actual value of `a0`. Looking at the kernel source I can see that an [`orig_a0`](https://github.com/torvalds/linux/blob/196145c606d0f816fd3926483cb1ff87e09c2c0b/arch/riscv/include/asm/ptrace.h#L52-L53) field exists in `struct pt_regs`, but AFAICT that's private data that we can't get access to from userspace...

I'm afraid this is as far as I'm able to go. Please let me know if I can provide additional information, test tentative patches, or do anything else to help get this fixed.

**Comment by ldv-alt** [comment] 2024-09-14 00:06
We test strace on riscv hosts provided by https://portal.cfarm.net/, and the test suite passes there.
In particular, it passes on the following hosts:
```
Linux cfarm93.cfarm.net 6.6.0-starfive2 #1 SMP Sat Jan 20 10:21:27 UTC 2024 riscv64 GNU/Linux
Linux cfarm92 6.5.0-35-generic #35.1~22.04.1-Ubuntu SMP Thu May  2 05:48:36 UTC 2024 riscv64 riscv64 riscv64 GNU/Linux
```
Also, strace used to pass tests on riscv before PTRACE_GET_SYSCALL_INFO API was introduced in the Linux kernel (by strace developers, FWIW).  If it no longer works, then it must be some riscv kernel regression.

Assuming that Linux kernel v6.6 works and whatever kernel you're working with doesn't, you can try to bisect the kernel and find the cause of this regression.

**Comment by andreabolognani** [comment] 2024-09-14 14:34
Bisecting might be problematic, as my hardware (VisionFive 2) only really got upstream support in 6.11. I can try installing Ubuntu on it and seeing whether the test passes there though.

A bisect inside a QEMU TCG VM would probably be feasible, if painfully slow.

Interestingly, the most recent [update from cfarm](https://portal.cfarm.net/news/51) talks about VisionFive 2 boards being added with recent Debian and Alpine, both of which should have recent kernels. Is there a way for you to get the CI jobs to run on those specific hosts?

**Comment by ldv-alt** [comment] 2024-09-14 14:58
Do you mean running CI jobs integrated into github actions workflow?  To be honest, I don't know.
We run tests there manually and they pass, this includes cfarm93, see above.

Btw, there was another riscv ptrace regression caught by strace test suite and fixed recently, see https://git.kernel.org/torvalds/c/61119394631f219e23ce98bcc3eb993a64a8ea64. Could it be that the fix introduced this new regression?

**Comment by ldv-alt** [comment] 2024-09-14 15:05
FWiW, 0xffffffffffffffda is `(long) -ENOSYS`, so yes, I'm pretty sure the regression you see is a side effect of that fix.

**Comment by andreabolognani** [comment] 2024-09-14 16:31
That definitely looks like it might be related! I can absolutely try to rebuild my kernel with that patch reverted and see whether the behavior noted here changes.

**Comment by andreabolognani** [comment] 2024-09-15 21:00
Okay, I just tried with the patched kernel (building it took a while) and the behavior is the expected one:

```
$ ./src/strace /
execve("/", ["/"], 0x3fe96a4230 /* 32 vars */) = -1 EACCES (Permission denied)
./src/strace: exec: Permission denied
+++ exited with 1 +++
$ ./src/disable_ptrace_get_syscall_info ./src/strace /
execve("/", ["/"], 0x3fc0262210 /* 32 vars */) = -1 EACCES (Permission denied)
./src/strace: exec: Permission denied
+++ exited with 1 +++
```

So this seems to confirm that [61119394631f](https://git.kernel.org/torvalds/c/61119394631f219e23ce98bcc3eb993a64a8ea64) did in fact cause a regression.

Now, how do we get about getting it fixed? It seems that you might already be well-versed in the process of reporting kernel bugs, while I'm not familiar with it at all, so I'm all ears :)

**Comment by andreabolognani** [comment] 2024-09-16 16:55
Reported [here](https://lore.kernel.org/all/CABJz62PRAv0QqszOTHDUdrrgY-Za9y9Vq6mYke=FqP=N5qXvbw@mail.gmail.com/).

**Comment by CoelacanthusHex** [comment] 2024-09-16 19:15
On the kernel side, we can't work around this **directly** because this needs we set `a0 = -ENOSYS` after `syscall_enter_from_user_mode()` or `syscall_handler()`, but another regression[^1] mentioned by @ldv-alt needs we set it before `syscall_enter_from_user_mode()`. The strace uses `a0` instead of `orig_a0` in riscv, unlike in loongarch. The strace does this because riscv doesn't export `orig_a0` in `user_regs_struct`. This API was designed by @palmer-dabbelt at https://github.com/torvalds/linux/commit/e2c0cdfba7f69925afc92b20cd9835d81e11a4f1.

There are two solutions:
1. Just add `orig_a0` in `user_regs_struct` and let strace use it, just like loongarch do.
2. Like powerpc, don't use the generic entry. Go back to the state before we switch to generic entry in 6.6.

I will post an RFC to add `orig_a0` in `user_regs_struct` in the mail list because this solution is furthermore elegant and natural since `a0` was used as both argument and return value in ABI.

[^1]: https://lore.kernel.org/linux-riscv/20240627071422.GA2626@altlinux.org/

**Comment by andreabolognani** [comment] 2024-09-16 19:48
With the caveat that I understand very little about both strace and the kernel, to the point where most of your explanation went way over my head :), making `orig_a0` available to userspace sounds very appealing to me, especially since loongarch64 already sets a precedent for doing that.

**Comment by esyr** [comment] 2024-09-16 23:04
>     1. Just add `orig_a0` in `user_regs_struct` and let strace use it, just like loongarch do.

You can't "just add" `orig_a0` to user_regs_struct, it will break the ABI.

>     2. Like powerpc, don't use the generic entry. Go back to the state before we switch to generic entry in 6.6.

The powerpc's ptrace history is pretty convoluted, but it seems to be the required way here as well, to avoid regressions for the existing software.

**Comment by CoelacanthusHex** [comment] 2024-09-16 23:17
> > ```
> > 1. Just add `orig_a0` in `user_regs_struct` and let strace use it, just like loongarch do.
> > ```
> 
> You can't "just add" `orig_a0` to user_regs_struct, it will break the ABI.

Yeah. user_regs_struct has no reserved data to expand it, unlike user_pt_regs of loongarch.

> 
> > ```
> > 2. Like powerpc, don't use the generic entry. Go back to the state before we switch to generic entry in 6.6.
> > ```
> 
> The powerpc's ptrace history is pretty convoluted, but it seems to be the required way here as well, to avoid regressions for the existing software.

I'm preparing an RFC to discuss the problem we faced and possible solutions.

**Comment by CoelacanthusHex** [comment] 2024-09-17 06:14
RFC was posted in https://lore.kernel.org/linux-riscv/59505464-c84a-403d-972f-d4b2055eeaac@gmail.com/T/

**Comment by esyr** [comment] 2024-09-17 12:22
I've actually mistaken, it's arm where strace uses a special regset, `NT_ARM_SYSTEM_CALL`, to tamper with the syscall number:
```
static int
arch_set_scno(struct tcb *tcp, kernel_ulong_t scno)
{
        unsigned int n = (uint16_t) scno;
        const struct iovec io = {
                .iov_base = &n,
                .iov_len = sizeof(n)
        };
        int rc = ptrace(PTRACE_SETREGSET, tcp->pid, NT_ARM_SYSTEM_CALL, &io);
        if (rc && errno != ESRCH)
                perror_func_msg("NT_ARM_SYSTEM_CALL pid:%d scno:%#x",
                                tcp->pid, n);
        return rc;
}
```
~ [src/linux/aarch64/set_scno.c](../blob/master/src/linux/aarch64/set_scno.c)


I guess, riscv revelopers might want to follow the same route.

**Comment by ldv-alt** [comment] 2024-11-06 23:26
> I've actually mistaken, it's arm where strace uses a special regset, `NT_ARM_SYSTEM_CALL`, to tamper with the syscall number:
> [...]
> I guess, riscv revelopers might want to follow the same route.

Just for the reference, they finally [decided](https://lore.kernel.org/all/CAJ+HfNj4d8_Ow1GyA3uX+2f79V8173e9RWfcX6_KjTPfinZCiw@mail.gmail.com/T/#u) that a new regset is needed.

**Comment by andreabolognani** [comment] 2024-11-07 09:48
@ldv-alt thanks for keeping track of this! I've been skimming the kernel threads I've been CC'd in, but once again a lot of it is going way above my head :)

In terms of getting strace to build on riscv64, do I understand correctly that we're going to need a new kernel containing the new interface _and_ changes to strace to make it use it?

**Comment by andreabolognani** [comment] 2024-12-02 14:04
Updating this ticket just to make sure that we have all information in one place and it's easier to track progress.

My understanding is that an [initial approach](https://lore.kernel.org/linux-riscv/20241017-fix-riscv-syscall-nr-v1-1-4edb4ca07f07@gmail.com/T/) was suggested, but it was found to be an incomplete fix, so a couple days ago a patch implementing a [different approach](https://lore.kernel.org/linux-riscv/20241201-riscv-new-regset-v1-1-c83c58abcc7b@coelacanthus.name/T/) was posted.

@CoelacanthusHex does the above look accurate?

@ldv-alt can you please confirm that strace would need changes so that it can consume the new API as a fallback to `PTRACE_GET_SYSCALL_INFO`? I wonder how that would play out in practice, since IIUC the fallback is mostly intended to accommodate older kernels while the new API will obviously only be available in new ones...

**Comment by CoelacanthusHex** [comment] 2024-12-03 09:31
> @ldv-alt can you please confirm that strace would need changes so that it can consume the new API as a fallback to `PTRACE_GET_SYSCALL_INFO`? I wonder how that would play out in practice, since IIUC the fallback is mostly intended to accommodate older kernels while the new API will obviously only be available in new ones...

Actually, the issue doesn't affect users. When the wrong change was introduced into the kernel (6.7), the PTRACE_GET_SYSCALL_INFO was there (5.3). The test failed because strace disabled it forcibly to test the old way on the new kernel. For the actual use environment, if a0 is ENOSYS, there will be PTRACE_GET_SYSCALL_INFO to get the current argument.
https://lore.kernel.org/linux-riscv/20241201-riscv-new-regset-v1-1-c83c58abcc7b@coelacanthus.name/T/ solves another issue: PTRACE_GET_SYSCALL_INFO can only get orig_a0, can't modify it. I don't know whether strace uses it.

**Comment by ldv-alt** [comment] 2024-12-03 12:32
> @ldv-alt can you please confirm that strace would need changes so that it can consume the new API as a fallback to `PTRACE_GET_SYSCALL_INFO`? I wonder how that would play out in practice, since IIUC the fallback is mostly intended to accommodate older kernels while the new API will obviously only be available in new ones...

In strace tests there is always an option to skip the test on a certain combination of the architecture and kernel version.

**Comment by ldv-alt** [comment] 2024-12-03 12:39
> Actually, the issue doesn't affect users. When the wrong change was introduced into the kernel (6.7), the PTRACE_GET_SYSCALL_INFO was there (5.3). The test failed because strace disabled it forcibly to test the old way on the new kernel.

The issue is indeed not likely to affect strace users, mainly because strace project was pioneering the PTRACE_GET_SYSCALL_INFO API, but there are still quite a few ptrace users that haven't adopted PTRACE_GET_SYSCALL_INFO yet.

> For the actual use environment, if a0 is ENOSYS, there will be PTRACE_GET_SYSCALL_INFO to get the current argument. https://lore.kernel.org/linux-riscv/20241201-riscv-new-regset-v1-1-c83c58abcc7b@coelacanthus.name/T/ solves another issue: PTRACE_GET_SYSCALL_INFO can only get orig_a0, can't modify it. I don't know whether strace uses it.

strace doesn't provide an interface to tamper with syscall arguments themselves yet, but there is a PR #259 for that.

**Comment by andreabolognani** [comment] 2024-12-03 12:50
> In strace tests there is always an option to skip the test on a certain combination of the architecture and kernel version.

@ldv-alt that's roughly what I was attempting with [fedora/strace#10](https://src.fedoraproject.org/rpms/strace/pull-request/10), which you rejected.

Do I understand correctly that, now that we have a clearer picture of the situation, you'd be open to consider something along those lines?

If you want things to be reworked so that the change happens upstream instead of downstream, or so that the kernel version is taken into account as well, I'm absolutely willing to work on that. I would need some guidance for the latter though :)

**Comment by ldv-alt** [comment] 2024-12-03 13:19
> If you want things to be reworked so that the change happens upstream instead of downstream, or so that the kernel version is taken into account as well, I'm absolutely willing to work on that. I would need some guidance for the latter though :)

Yes, I definitely prefer an upstream patch.
Here is some guidance, inspired by `require_min_kernel_version_or_skip()` :)
Completely untested, though.

```
# Usage: skip_kernel_version_range 6.7 6.12
skip_kernel_version_range()
{
        local uname_r code
        uname_r="$(uname -r)"
        code="$(kernel_version_code "$uname_r")"

        if [ "$code" -ge "$(kernel_version_code "$1")" ] &&
           [ "$code" -le "$(kernel_version_code "$2")" ]; then
                skip_ "the kernel release $uname_r is within $1..$2 range"
        fi
}
```

**Comment by andreabolognani** [comment] 2024-12-03 15:07
@ldv-alt great pointers, thanks.

One more question about the version range.

The lower bound should be 6.11 I think, since that's the release that contains [61119394631f](https://git.kernel.org/torvalds/c/61119394631f219e23ce98bcc3eb993a64a8ea64) which caused the regression, so anything up to that should be able to successfully run the test.

As for the upper bound... I'm still unclear whether [the proposed patch](https://lore.kernel.org/linux-riscv/20241201-riscv-new-regset-v1-1-c83c58abcc7b@coelacanthus.name/T/) actually gets us back to the pre-6.11 days, where we could get the information we needed without using the `PTRACE_GET_SYSCALL_INFO` API? Based on [the comment above](https://github.com/strace/strace/issues/315#issuecomment-2513992340), it sounds like it won't.

So I wonder if we're not really looking at a `require_max_kernel_version_or_skip()` in the end, so that we can ensure that the test is only executed on riscv64 when the kernel is older than 6.11.

**Comment by ldv-alt** [comment] 2024-12-03 15:31
> So I wonder if we're not really looking at a `require_max_kernel_version_or_skip()` in the end, so that we can ensure that the test is only executed on riscv64 when the kernel is older than 6.11.

Once the kernel gets the fix merged and strace starts using it, the very same test could be used to test it in strace.
We can omit the upper bound check for now, but we would have to reintroduce it later when both the kernel and strace will be ready to be tested.

**Comment by ldv-alt** [comment] 2024-12-03 16:16
> Okay but testing the fix will require changes to the test program, right?

I don't think the test will require changes besides specifying the upper bound for the kernel version range.

> The existing code won't just start working again as-is.

This is correct because strace itself would have to support this new riscv regset before the test could be enabled.

**Comment by andreabolognani** [comment] 2024-12-04 13:16
> I don't think the test will require changes besides specifying the upper bound for the kernel version range.

@ldv-alt right, I failed to realize that the test in question is purely script-based and so would continue to be applicable even if the internals of strace have to be modified :)

Anyway, I just created #330 which should get things working on current kernels while we wait for the new API to show up.

**Closed** 2024-12-05 10:59 UTC
Labels: external-bugs/kernel
