### ISSUE TITLE
6.1 test failures on mips64el and mipsel

### ISSUE THREAD

**Issue by andhe** [strace/strace#235] opened 2023-01-27 19:57 UTC
Hello,

I tried to upload 6.1 to Debian (experimental) as got test failures on mips64el and mipsel architectures.

The full build logs are available at:
* https://buildd.debian.org/status/fetch.php?pkg=strace&arch=mips64el&ver=6.1-0.1%7Eexp2&stamp=1674843235&raw=0
* https://buildd.debian.org/status/fetch.php?pkg=strace&arch=mipsel&ver=6.1-0.1%7Eexp2&stamp=1674844648&raw=0

I tried to analyze the logs and as far as I can tell the failures boils down to:

# mips64el

ptrace_syscall_info seem to be the root cause for all test failures!

```
../../tests/ptrace_syscall_info.c:246: ../../tests/ptrace_syscall_info.c:246: #1: entry stop mismatch
```

# mipsel

Most test-case failures are caused by (or a variant of this test segfaulting):
```
+ ../sockopt-sol_socket
Segmentation fault
```

But there are also multiple tests that fails for various reasons (diff between expected and output).

(There are also failures on other non-release architectures that can currently be seen at: https://buildd.debian.org/status/package.php?p=strace&suite=experimental  ... click the status column for respective architecture for full build log.)

**Comment by ldv-alt** [comment] 2023-02-03 16:34
Someone with an access to such hardware would need to have a look.

**Comment by parport0** [comment] 2023-02-18 19:35
mips64el:
```
--- expected
+++ actual
@@ -124,4 +124,6 @@
 ptrace(PTRACE_GET_SYSCALL_INFO, 138, 29, {op=PTRACE_SYSCALL_INFO_ENTRY, arch=AUDIT_ARCH_MIPSEL64, instruction_pointer=0xfff34dd930, stack_pointer=0xfffbf992d8}) = 80
 ptrace(PTRACE_GET_SYSCALL_INFO, 138, 30, {op=PTRACE_SYSCALL_INFO_ENTRY, arch=AUDIT_ARCH_MIPSEL64, instruction_pointer=0xfff34dd930, stack_pointer=0xfffbf992d8}) = 80
 ptrace(PTRACE_GET_SYSCALL_INFO, 138, 31, {op=PTRACE_SYSCALL_INFO_ENTRY, arch=AUDIT_ARCH_MIPSEL64, instruction_pointer=0xfff34dd930, stack_pointer=0xfffbf992d8}) = 80
-ptrace(PTRACE_GET_SYSCALL_INFO, 138, 32, {op=PTRACE_SYSCALL_INFO_ENTRY, arch=AUDIT_ARCH_MIPSEL64, instruction_pointer=0xfff34dd930, stack_pointer=0xfffbf992d8
\ No newline at end of file
+ptrace(PTRACE_GET_SYSCALL_INFO, 138, 32, {op=PTRACE_SYSCALL_INFO_ENTRY, arch=AUDIT_ARCH_MIPSEL64, instruction_pointer=0xfff34dd930, stack_pointer=0xfffbf992d8, entry={nr=__NR_ptrace}}) = 80
+ptrace_syscall_info.c:246: ptrace_syscall_info.c:246: #1: entry stop mismatch
++++ exited with 1 +++
```

**Comment by ldv-alt** [comment] 2023-02-18 20:34
This looks like a kernel regression, on
```
Linux erlite 4.19.0-rc5-00143-gc307aaf3eb47 #1 SMP Tue Oct 9 00:32:47 CEST 2018 mips64 GNU/Linux
```
these tests pass:
```
PASS: ptrace_syscall_info.gen.test
PASS: ptrace_syscall_info-Xabbrev.gen.test
PASS: ptrace_syscall_info-Xverbose.gen.test
PASS: ptrace_syscall_info-Xraw.gen.test
```

**Comment by parport0** [comment] 2023-02-18 20:39
Fail on:
`Linux buildroot 6.1.11 #1 SMP Sat Feb 18 12:25:11 CET 2023 mips64 GNU/Linux`

BTW, the full call looks like this:
`ptrace(PTRACE_GET_SYSCALL_INFO, 149, 88, {op=PTRACE_SYSCALL_INFO_ENTRY, arch=AUDIT_ARCH_MIPSEL64, instruction_pointer=0xfff38ed930, stack_pointer=0xfffbb02e08, entry={nr=__NR_ptrace, args=[0xaaaacd40d8, 0xbad1fed1, 0xbad2fed2, 0xbad3fed3, 0xbad4fed4, 0xbad5fed5]}}) = 80`

**Comment by ldv-alt** [comment] 2023-02-18 21:39
OK, it's a mips linux kernel regression introduced by linux kernel commit v3.19~11^2~1, and the kernel fix should be trivial.

**Comment by ldv-alt** [comment] 2023-02-18 22:57
The fix for this mips kernel bug is [submitted](https://lore.kernel.org/lkml/20230218233212.1fed456b@akathisia/T/#u).

**Comment by ldv-alt** [comment] 2023-02-27 00:38
> The fix for this mips kernel bug is [submitted](https://lore.kernel.org/lkml/20230218233212.1fed456b@akathisia/T/#u).

And [merged](https://github.com/torvalds/linux/commit/85cc91e2ba42) to the mainline tree.

**Comment by ldv-alt** [comment] 2023-04-29 12:33
The kernel bug was fixed upstream and backported to stable branches, thanks to everybody involved, closing the issue.

**Closed by ldv-alt** 2023-04-29 12:33 UTC
Labels: kernel bug
